---
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    labels:
      - dependencies
      - python
    groups:
      py-minor-and-patch:
        update-types:
          - minor
          - patch
    schedule:
      interval: weekly
      day: friday
      time: 17:00
      timezone: America/Chicago
    cooldown:
      default-days: 5 # zizmor: ignore[dependabot-cooldown]
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3

  - package-ecosystem: npm
    directory: /
    labels:
      - dependencies
      - javascript
      - npm
    groups:
      npm-minor-and-patch:
        update-types:
          - minor
          - patch
    schedule:
      interval: weekly
      day: friday
      time: 17:00
      timezone: America/Chicago
    cooldown:
      default-days: 5 # zizmor: ignore[dependabot-cooldown]
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3

  - package-ecosystem: github-actions # zizmor: ignore[dependabot-cooldown]
    directory: /
    labels:
      - dependencies
      - github_actions
    groups:
      gha-minor-and-patch:
        update-types:
          - minor
          - patch
    schedule:
      interval: weekly
      day: friday
      time: 17:00
      timezone: America/Chicago

  - package-ecosystem: pre-commit # zizmor: ignore[dependabot-cooldown]
    directory: /
    labels:
      - dependencies
      - dev
    groups:
      pre-commit-minor-and-patch:
        update-types:
          - minor
          - patch
    schedule:
      interval: weekly
      day: friday
      time: 17:00
      timezone: America/Chicago
