[[configs]]
  FileName = "docker-compose.yaml"
  Name     = "docker-compose"
  Schemas  = ["compose-spec.json"]

[[configs]]
  FileName = ".golangci.yaml"
  Name     = "golangci-lint"
  Schemas  = ["v1.json", "v2.json"]

[[configs]]
  FileName = ".goreleaser.yaml"
  Name     = "goreleaser"
  Schemas  = ["pro.json", "schema.json"]

[[configs]]
  FileName = ".pre-commit-config.yaml"
  Name     = "pre-commit-config"
  Schemas  = ["pre-commit-config.json"]

[[configs]]
  FileName = ".pre-commit-hooks.yaml"
  Name     = "pre-commit-hooks"
  Schemas  = ["pre-commit-hooks.json"]

[[configs]]
  FileName = ".prettierrc"
  Name     = "prettierrc"
  Schemas  = ["prettierrc.json"]

[[configs]]
  FileName = "pyproject.toml"
  Name     = "pyproject"
  Schemas  = ["pyproject.json"]
