[[configs]]
  FileName = ".golangci.yaml"
  Name     = "golangci-lint"
  Schemas  = ["v1.json", "v2.json"]

[[configs]]
  FileName = ".goreleaser.yaml"
  Name     = "goreleaser"
  Schemas  = ["schema.json", "pro.json"]

[[configs]]
  FileName = ".pre-commit-config.yaml"
  Name     = "pre-commit-config"
  Schemas  = ["pre-commit-config.json"]

[[configs]]
  FileName = "pyproject.toml"
  Name     = "pyproject"
  Schemas  = ["pyproject.json"]

[[configs]]
  FileName = ".prettierrc"
  Name     = "prettierrc"
  Schemas  = ["prettierrc.json"]
