name: Go - Audit

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"
  push:
    branches: ["*"]
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  audit-reusable:
    uses: esacteksab/.github/.github/workflows/go-ci.yml@f6ca4d5de20efe4818ca1511619a39ff5e11f6bb #v0.16.0
