name: Go - Audit

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"
  push:
    branches: ["*"]
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  audit-reusable:
    uses: esacteksab/.github/.github/workflows/go-ci.yml@f2ba3f6b02af9b437a8224d8a6693421a1a65cca  # v0.80.30
