name: Go - Audit

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"
  push:
    branches: ["*"]
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  audit-reusable:
    uses: esacteksab/.github/.github/workflows/go-ci.yml@5fde5a83a2230ae79ce89fafd3840893e2af9b7a  # v0.20.0
