name: Go - Test

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"
  push:
    branches: ["*"]
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  go-test:
    uses: esacteksab/.github/.github/workflows/go-test.yml@ba7696551c4438b75c8a70ecf73c43a1dc411c49  # v0.82.4
