name: Go - Test

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"
  push:
    branches: ["*"]
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  go-test:
    uses: esacteksab/.github/.github/workflows/go-test.yml@4e572af21b05e3621a98caabda5df594e5bd93b8  # v0.85.3
