name: Labeler

on:
  pull_request:
    types:
      - opened

permissions:
  contents: read
  pull-requests: write

jobs:
  label-pr:
    uses: esacteksab/.github/.github/workflows/labeler.yml@a25d4150e0f10a9b686d890a6ba5503bc7d14558  # v0.80.2
